config/routes.rb
Rails.application.routes.draw do
  # devise_for :admins
  # devise_for :admins, controllers: {
  #   sessions: 'admins/sessions'
  # }


  # devise_for :admins, controllers: {
  # 	sessions: "admins/sessions",
  # 	passwords: 'admins/passwords',
  #   registrations: 'admins/registrations'
  # }
  devise_for :admins, skip: :all
  devise_scope :admin do
    get 'admins/sign_in' => 'admins/sessions#new', as: 'new_admin_session'
    post 'admins/sign_in' => 'admins/sessions#create', as: 'admin_session'
    delete 'admins/sign_out' => 'admins/sessions#destroy', as: 'destroy_admin_session'
  end

  devise_for :customers, skip: :all
  devise_scope :customer do
    get 'customers/sign_in' => 'public/sessions#new', as: 'new_customer_session'
    post 'customers/sign_in' => 'public/sessions#create', as: 'customer_session'
    delete 'customers/sign_out' => 'public/sessions#destroy', as: 'destroy_customer_session'
    get 'customers/sign_up' => 'public/registrations#new', as: 'new_customer_registration'
    post 'customers' => 'public/registrations#create', as: 'customer_registration'
    get 'customers/password/new' => 'public/passwords#new', as: 'new_customer_password'
  end


  namespace :admins do
    get 'homes/top'
  end
  namespace :admins do
    get 'orders/index'
    get 'orders/show'
  end
  # devise_for :customers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'homes/about' => 'public/homes#about'
  get 'public/homes/top' => 'public/homes#top'
  get 'public/homes/top2' => 'public/homes#top2'
  get 'admins/homes/top' => 'public/homes#top'
  # post 'public/cart_items' => 'cart_items#add_item'

  root 'public/homes#top'

  namespace 'admins' do
    resources :customers, only: [:index, :create, :show, :edit, :update]
    resources :items
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :orders, only: [:index, :show, :update] do
      patch :toggle_status
    end
    resources :order_details, only:[:update]
  end

  namespace 'public' do
    resources :items, only: [:index, :show]
    resources :customers, only: [:new, :create, :show, :edit, :update] do
      member do
        get 'check'
        patch 'withdrawl'
      end
    end
    #   collection do
    #     patch :toggle_status
    #   end
    # end
    resources :addresses, only: [:index, :show, :create, :edit, :update, :destroy]
    resources :orders, only: [:index, :show, :new, :create] do
      collection do
        post :confirm
        get :complete
      end
    end
    resources :cart_items, only: [:index, :update, :create, :destroy, :show] do
      collection do
        delete 'destroy_all'
      end
    end
  end

  get 'public/customers/unsubscribe/:id' => 'public/customers#unsubscribe', as: 'customers_unsubscribe'

  scope 'admin' do
    resources :orders, only: [:index, :show, :update]
  end







  # get 'orders/new' => 'orders#new'

  # post 'orders' => 'orders#create'
  # get 'orders/index' => 'orders#index'
  # get "orders/show" => 'orders#show'

  scope 'admin' do
    resources :order_details, only: [:update]
  end

  delete 'public/destroy_all' => 'public#destroy_all'

end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_detales, dependent: :destroy
  
  belongs_to :genre
  attachment :image
  # has_one_attached :image
end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    # binding.pry
    @item.save
    redirect_to admins_item_path(@item.id)
  end

  def index
    @items = Item.all
    @genres = Genre.all
    # binding.pry
  end

  def show
    @item = Item.find(params[:id])
    # binding.pry
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
    # binding.pry
  end

  def update
    @item = Item.find(params[:id])
    # binding.pry
    @item.update(item_params)
    # binding.pry
    redirect_to admins_items_path
  end

  def destroy
    @item = Item.find(params[:id])
    # byebug
    @item.destroy
    redirect_to admins_items_path
  end

  private
  def item_params
    params.require(:item).permit(
      :image,
      :name,
      :introduction,
      :genre_id,
      :price,
      :is_active)
  end

end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/views/admins/items/back_new.html.erb
<div class="container">
  <div class="row">
    <header>
      <div class="function_title">
        <h2>商品新規登録</h2>
      </div>
    </header>
    <div class="container">
      <%= form_with model: @item, url: admins_items_path, local: true do |f| %>
      <div class="col-xs-5">
        <div class="form-group has-icon">
          <%= attachment_image_tag @item, :image, format: 'jpg', fallback: "no_image.jpg", size: "200x200" %>
          <%= f.attachment_field :image %>
        </div>
      </div>
      <div class="col-xs-7">
        <div class="row">
          <div class="col-xs-4">商品名</div>
          <div class="col-xs-8"><%= f.text_field :name %></div>
        </div>
        <div class="row">
          <div class="col-xs-4">商品説明</div>
          <div class="col-xs-8"><%= f.text_field :introduction %></div>
        </div>
        <div class="row">
          <div class="col-xs-4">ジャンル</div>
          <div class="col-xs-8"><%= f.collection_select :genre_id, @genres, :id, :name, include_blank: "選択して下さい" %></div>
        </div>
        <div class="row">
          <div class="col-xs-4">税込価格（税抜価格）</div>
          <div class="col-xs-8"><%= f.text_field :price %></div>
        </div>
        <div class="row">
          <div class="col-xs-4">販売ステータス</div>
          <div class="col-xs-8"><%= f.select :is_active, [["販売中", "true"], ["未販売", "false"]], include_blank: "選択して下さい" %></div>
          <div class="switch"><%= f.submit "新規登録", class:"btn btn-danger" %></div>
        </div>
  
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admins/items/edit.html.erb
<div class="container">
  <header>
    <div class="function_title">
      <h2>商品詳細</h2>
    </div>
  </header>
  <div class="row">
    <%= form_with model: @item, url: admins_item_path, local: true do |f| %>
    <div class="col-xs-3">
      <div class="form-group has-icon">
        <%= attachment_image_tag @item, :image, format: 'jpg', fallback: "no_image.jpg", size: "200x200" %> 
        <%= f.attachment_field :image %>
      </div>
    </div>
    <div class="col-xs-9">
      <table class="table-striped">
        <tr class="box"><td>商品名</td><td><%= f.text_field :name %></td></tr>
        <tr class="box"><td>商品説明</td><td><%= f.text_field :introduction %></td></tr>
        <tr class="box"><td>ジャンル</td><td><%= f.collection_select :genre_id, @genres, :id, :name, include_blank: "選択して下さい" %></td></tr>
        <tr class="box"><td>税込価格（税抜価格）</td><td><%= f.text_field :price %></td></tr>
        <tr class="box"><td>販売ステータス</td><td><%= f.select :is_active, [["販売中", "true"], ["計画中", "false"]], include_blank: "選択して下さい" %></td></tr>
      </table>
      <div class="switch_left"><%= f.submit "編集を保存する",  class:"btn btn-primary" %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/admins/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs">
      <div class="function_title">
        <h2>商品一覧</h2>
      </div>

      <div class="newb"><%= link_to "＋", new_admins_item_path %></div>
        <table class="table table-striped">
          <thead class="head_data">
            <tr>
              <th>ID</th>
              <th>商品名</th>
              <th>税抜価格</th>
              <th>ジャンル</th>
              <th>ステータス</th>
              <th></th>
            </tr>
          </thead>
          <tbody class="item_data">
            <% @items.each do |item| %>
            <tr>
              <td><%= item.id %></td>
              <td><%= link_to item.name, admins_item_path(item.id) %></td>
              <td class="price"><%= item.price.to_s(:delimited) %></td>
              <td><%= item.genre.name %></td>
              <td>
                <% if item.is_active %>
                  販売中
                <% else %>
                  計画中
                <% end %>
              </td>
              <td><%#= link_to "削除", admins_item_path(item.id), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger" %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

app/views/admins/items/new.html.erb
<div class="container">
  <header>
    <div class="function_title">
      <h2>商品新規登録</h2>
    </div>
  </header>
  <div class="row">
    <%= form_with model: @item, url: admins_items_path, local: true do |f| %>
    <div class="col-xs-3">
      <div class="form-group has-icon">
        <%= attachment_image_tag @item, :image, format: 'png', fallback: "no_image.jpg", size: "200x200" %>
        <%= f.attachment_field :image %>
      </div>
    </div>
    <div class="col-xs-9">
      <table class="table-striped">
        <tr class="box"><td>商品名</td><td><%= f.text_field :name %></td></tr>
        <tr class="box"><td>商品説明</td><td><%= f.text_field :introduction %></td></tr>
        <tr class="box"><td>ジャンル</td><td><%= f.collection_select :genre_id, @genres, :id, :name, include_blank: "選択して下さい" %></td></tr>
        <tr class="box"><td>税込価格（税抜価格）</td><td><%= f.text_field :price %></td></tr>
        <tr class="box"><td>販売ステータス</td><td><%= f.select :is_active, [["販売中", "true"], ["計画中", "false"]], include_blank: "選択して下さい" %></td></tr>
      </table>
      <div class="switch_right"><%= f.submit "新規登録" %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/admins/items/show.html.erb
<div class="container">
  <header>
    <div class="function_title">
      <h2>商品詳細</h2>
    </div>
  </header>
  <div class="row">
    <%= form_with model: @item, url: admins_item_path, local: true do |f| %>
    <div class="col-xs-3">
      <div class="form-group has-icon">
      <%= attachment_image_tag @item, :image, format: 'png', fallback: "no_image.jpg", size: "200x200" %>
      </div>
    </div>
    <div class="col-xs-9">
      <table class="table-striped">
        <tr class="box"><td>商品名</td><td><%= @item.name %></td></tr>
        <tr class="box"><td>商品説明</td><td><%= @item.introduction %></td></tr>
        <tr class="box"><td>ジャンル</td><td><%= @item.genre.name %></td></tr>
        <tr class="box"><td>税込価格（税抜価格）</td><td><%= (@item.price*1.1).floor %>円（<%= @item.price %>円）</td></tr>
        <tr class="box"><td>販売ステータス</td>
          <td>
            <% if @item.is_active %>
            販売中
            <% else %>
            計画中
            <% end %>
            
          </td>
        </tr>
        
      </table>
      <div class="switch_left"><%= link_to "編集する", edit_admins_item_path(@item.id), class:"btn btn-primary" %></div>
      <% end %>
    </div>
  </div>
  
</div>