config/routes.rb
Rails.application.routes.draw do
  # devise_for :admins
  # devise_for :admins, controllers: {
  #   sessions: 'admins/sessions'
  # }


  # devise_for :admins, controllers: {
  # 	sessions: "admins/sessions",
  # 	passwords: 'admins/passwords',
  #   registrations: 'admins/registrations'
  # }
  devise_for :admins, skip: :all
  devise_scope :admin do
    get 'admins/sign_in' => 'admins/sessions#new', as: 'new_admin_session'
    post 'admins/sign_in' => 'admins/sessions#create', as: 'admin_session'
    delete 'admins/sign_out' => 'admins/sessions#destroy', as: 'destroy_admin_session'
  end

  devise_for :customers, skip: :all
  devise_scope :customer do
    get 'customers/sign_in' => 'public/sessions#new', as: 'new_customer_session'
    post 'customers/sign_in' => 'public/sessions#create', as: 'customer_session'
    delete 'customers/sign_out' => 'public/sessions#destroy', as: 'destroy_customer_session'
    get 'customers/sign_up' => 'public/registrations#new', as: 'new_customer_registration'
    post 'customers' => 'public/registrations#create', as: 'customer_registration'
    get 'customers/password/new' => 'public/passwords#new', as: 'new_customer_password'
  end


  namespace :admins do
    get 'homes/top'
  end
  namespace :admins do
    get 'orders/index'
    get 'orders/show'
  end
  # devise_for :customers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'homes/about' => 'public/homes#about'
  get 'public/homes/top' => 'public/homes#top'
  get 'public/homes/top2' => 'public/homes#top2'
  get 'admins/homes/top' => 'public/homes#top'
  # post 'public/cart_items' => 'cart_items#add_item'

  root 'public/homes#top'

  namespace 'admins' do
    resources :customers, only: [:index, :create, :show, :edit, :update]
    resources :items
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :orders, only: [:index, :show, :update] do
      patch :toggle_status
    end
    resources :order_details, only:[:update]
  end

  namespace 'public' do
    resources :items, only: [:index, :show]
    resources :customers, only: [:new, :create, :show, :edit, :update] do
      member do
        get 'check'
        patch 'withdrawl'
      end
    end
    #   collection do
    #     patch :toggle_status
    #   end
    # end
    resources :addresses, only: [:index, :show, :create, :edit, :update, :destroy]
    resources :orders, only: [:index, :show, :new, :create] do
      collection do
        post :confirm
        get :complete
      end
    end
    resources :cart_items, only: [:index, :update, :create, :destroy, :show] do
      collection do
        delete 'destroy_all'
      end
    end
  end

  get 'public/customers/unsubscribe/:id' => 'public/customers#unsubscribe', as: 'customers_unsubscribe'

  scope 'admin' do
    resources :orders, only: [:index, :show, :update]
  end







  # get 'orders/new' => 'orders#new'

  # post 'orders' => 'orders#create'
  # get 'orders/index' => 'orders#index'
  # get "orders/show" => 'orders#show'

  scope 'admin' do
    resources :order_details, only: [:update]
  end

  delete 'public/destroy_all' => 'public#destroy_all'

end

app/controllers/admins/homes_controller.rb
class Admins::HomesController < ApplicationController

  def top
    # @orders = Order.where(
    #   "created_at between '#{Date.today} 0:00:00' and '#{Date.today} 23:59:59'")
    # @itmes = Item.all
    @orders = Order.where("created_at >= ?", Date.today)
    # byebug
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
    @items = Item.all
    # binding.pry
    @order_details =  OrderDetail.find(
      OrderDetail.group(:item_id).order('count(item_id) desc').limit(3).pluck(:item_id))
      # binding.pry
    @genres = Genre.all
  end

  def top2

  end

  def about
  end

end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_genre.html.erb
<h2>ジャンル検索</h2>
<th>ジャンルをお選び下さい</th>

app/views/homes/about.html.erb
<div class="container">
  <div class="about">
    <h1>about</h1>
    <div class="promotion">
      ながのCakeは全国発送可能なケーキ屋さんです。</br>
      お子様からお年寄りの方までお召し上がりいただけるよう、</br>
      様々なバリエーションをご用意しております。</br>
      また、全国へ発送可能ですので「いつ」でも「どこ」でもご注文いただけます。</br>
      ぜひご注文ください。
    </div>
    <div class="shortcakeimage"></div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h3>ジャンル検索</h3>
        <table class="table table-striped">
          <tr>
            <th>ジャンル</th>
          </tr>
          <% @genres.each do |genre| %>
          <tr>
            <td><%= link_to genre.name, public_items_path %></td>
          </tr>
          <% end %>
        </table>
      </div>
    <div class="col-md-9">
      <h3></h3>
      <div class="cakeimage"></br></br></br>
        <div class="overview">
          ようこそ、NaganoCakeへ！</br>
        このサイトは、ケーキ販売のECサイトになります。</br>
        会員でない方も商品の閲覧はできますが、</br>
        購入には会員登録が必要になります。
        </div>
       </div>
      <div class="card-deck">
        <% @order_details.each do |order| %>
          <div class="col-md-4">
              <div class="card">
                <div class="card-img-top">
                  <%#= form_with model: order, local: true do |f| %>
                  <%= attachment_image_tag @item, :image, format: 'png', fallback: "no_image.jpg", size: "100x100" %>
                  <%# end %>
                </div>
                <div class="card-body">
                  <h5 class="card-title">
                    <%= order.item.name %>
                  </h5>
                  <p class="price">
                    <%= (order.item.price*1.1).floor %>円
                  </p>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
</div

app/views/homes/top2.html.erb
<div class="container">
  <div class="row">

    <h1>トップページ作成中です。</h1>
    <h3>少々お待ち下さい。</h3></br></br>

    <div>画面がまだ</div>

    <div><%= link_to "admins_orders_path", admins_orders_path(current_customer) %>　</div>
    <div><%= link_to "public_cart_items", public_cart_items_path(current_customer) %>　表示できない</div>
    <div><%= link_to "homes-about", homes_about_path %></div>
    <div><%= link_to "admins_homes_top", admins_homes_top_path %></div>

    </br></br><div>画面完成</div>
    <div>admins</div>
    <div><%= link_to "admins_customers", admins_customers_path %>　OK!</div>
    <div><%= link_to "admins_items", admins_items_path %>　OK!</div>
    <div><%= link_to "admins_genres", admins_genres_path %>　OK!</div>

    </br><div>public</div>
    <div><%= link_to "new_customer_registration", new_customer_registration_path %>　emailとpassword以外保存されていない</div>
    <div><%= link_to "public_items", public_items_path %>　OK!</div>

    <div><%= link_to "cart_item カート", public_cart_items_path %>　数量のアップデートができない</div>
    <div>退会処理ができておらず。　マイページ→編集→退会→退会（boolean型trueへ）</div>
  </div>
</div>